#!/bin/bash
# Carrier Pigeon daemon
# chkconfig: 345 68 32
# description: Carrier Pidgeon Message Queue Service
# processname: php
#
### BEGIN INIT INFO
# Provides: carrierpigeon 
# Required-Start: $local_fs $network $named
# Required-Stop: $local_fs $network $named
# Short-Description: Carrier Pidgeon Message Queue Service
# Description: Carrier Pidgeon Message Queue Service
### END INIT INFO

# Source function library.
. /etc/init.d/functions

DAEMON="/usr/bin/php"
DAEMONOPTS="/opt/CarrierPigeon/MessageQueue/MessageQueue.php"

DAEMONUSER="cpigeon"
NAME="carrierpigeon"
DESC="Carrier Pidgeon Message Queue Service"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

START_OPTS="--start --background --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} ${DAEMONOPTS}"
STOP_OPTS="--stop --pidfile ${PIDFILE}"
LOGFILE="/var/log/carrierpigeon"

case "$1" in
start)
    printf "%-50s" "Starting $NAME..."
    start-stop-daemon $START_OPTS >> $LOGFILE
;;
status)
    printf "%-50s" "Checking $NAME..."
    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
            printf "%s\n" "Process dead but pidfile exists"
        else
            echo "Running"
        fi
    else
        printf "%s\n" "Service not running"
    fi
;;
stop)
    printf "%-50s" "Stopping $NAME"
    if [ -f $PIDFILE ]; then
        start-stop-daemon $STOP_OPTS
        rm -f $PIDFILE
    else
        printf "%s\n" "pidfile not found"
    fi
;;

restart)
    $0 stop
    $0 start
;;

*)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac