#!/bin/bash
# Carrier Pigeon daemon
# chkconfig: 345 68 32
# description: Carrier Pidgeon Message Queue Service
# processname: php
#
### BEGIN INIT INFO
# Provides: carrierpigeon 
# Required-Start: $local_fs $network $named
# Required-Stop: $local_fs $network $named
# Short-Description: Carrier Pidgeon Message Queue Service
# Description: Carrier Pidgeon Message Queue Service
### END INIT INFO

# Source function library.
. /etc/init.d/functions

DAEMON_PATH="/opt/CarrierPigeon/MessageQueue"

DAEMON="/usr/bin/php"
DAEMONOPTS="/opt/CarrierPigeon/MessageQueue/MessageQueue.php"

DAEMONUSER="cpigeon"
NAME="carrierpigeon"
DESC="Carrier Pidgeon Message Queue Service"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

LOGFILE="/var/log/carrierpigeon"

case "$1" in
start)
  printf "%-50s" "Starting $NAME..."
  cd $DAEMON_PATH
  PID=`$DAEMON $DAEMONOPTS > $LOGFILE 2>&1 & echo $!`
  #echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
    $0 stop
    $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac