CREATE SCHEMA carrier_pidgeon; 
SET SCHEMA = carrier_pidgeon;

DROP TABLE Message;
DROP TABLE Group_JT;
DROP TABLE Groups;
DROP TABLE Person;
DROP TABLE Carrier;

create table Carrier
(
  carrierId int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  carrierName varchar(80) NOT NULL,
  emailAddress varchar(80) NOT NULL
)

create table Person
(
  uniqueId int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  firstName varchar(80) NOT NULL,
  lastName varchar(80) NOT NULL,
  emailAddress varchar(80) NOT NULL,
  verifyCode int,
  verifyCodeExp int,
  passwordHash varchar(80),
  phoneNumber varchar(15),
  carrierID int,
  isUser boolean,
  ownerId int,
  FOREIGN KEY (carrierId) REFERENCES Carrier (carrierId)
)

create table Groups
(
  groupId int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  groupName varchar(80),
  ownerId int NOT NULL,
  FOREIGN KEY (ownerId) REFERENCES Person (uniqueId)
)

create table Group_JT
(
  primary_key int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  groupOwnerId int NOT NULL,
  groupId int NOT NULL,
  FOREIGN KEY (groupOwnerId) REFERENCES Person (uniqueId),
  FOREIGN KEY (groupId) REFERENCES Groups (groupId)
)

create table Message
(
  messageId int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ownerId int NOT NULL,
  groupId int NOT NULL,
  subject varchar(80) NOT NULL,
  content clob,
  lastSent date,
  templateName varchar(80),
  FOREIGN KEY (ownerId) REFERENCES Person (uniqueId),
  FOREIGN KEY (groupId) REFERENCES Groups (groupId)
)